-- status 库建表（PostgreSQL）
-- 标识符一律不加引号：PG 会统一折叠为小写（代码里的 errIng 实际是 erring 表）

-- ip 不加 UNIQUE：upsert 以 hostname 为冲突仲裁，IP 在主机间流转时库级 ip 唯一约束会让启动 upsert 直接 23505 崩溃
CREATE TABLE IF NOT EXISTS vps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hostname varchar(255) NOT NULL UNIQUE,
  ip bytea NOT NULL
);

CREATE TABLE IF NOT EXISTS srv (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  val varchar(255) NOT NULL UNIQUE,
  -- 服务首次注册时间（秒），状态页可用率的观测窗口起点
  ctime bigint NOT NULL DEFAULT (extract(epoch from now()))::bigint
);

CREATE TABLE IF NOT EXISTS txt (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hash bytea NOT NULL UNIQUE,
  val text
);

CREATE TABLE IF NOT EXISTS errIng (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vps_id bigint NOT NULL,
  srv_id bigint NOT NULL,
  txt_id bigint NOT NULL,
  ts bigint NOT NULL,
  UNIQUE (vps_id, srv_id)
);

-- id 沿用 errIng 的 id（代码显式写入），非自增
CREATE TABLE IF NOT EXISTS errFixed (
  id bigint PRIMARY KEY,
  srv_id bigint NOT NULL,
  vps_id bigint NOT NULL,
  txt_id bigint NOT NULL,
  begin bigint NOT NULL,
  duration bigint NOT NULL
);
